import { DocsRouterNode, DocsRouterInfoDict } from "@/config/types"

export type SiteConfig = typeof siteConfig

export const siteConfig = {
    name: "Goframe",
    description:
        "GoFrame is a modular, high-performance, enterprise-level Go development framework. It is a general-purpose foundational framework that serves as an enhanced extension to the Golang standard library, encompassing versatile core components for development. Its strengths lie in its practicality, modularity, comprehensive documentation, rich modules, high usability, strong generality, and team-oriented design. GoFrame is suitable for developing both full-fledged engineering projects and as a toolkit due to its decoupled modular design. Whether you're looking to develop a business-oriented project in Golang, small or large-scale, GoFrame is your top choice. If you aim to create a Golang component library, GoFrame's ready-to-use, powerful foundational component library will greatly increase your efficiency.",
    keywords: ["goframe", "goframe framework", "goframe website", "goframe documentation", "gf", "gf framework", "gf website", "gf documentation"],
    mainNav: [
        {
            title: "Home",
            href: "/",
        },
    ],
    links: {
        github: "https://github.com/gogf/gf",
    },
}

export const routerNodeTree: DocsRouterNode[] = [
    {
        name: 'Quick Start',
        fullPath: '/docs',
        markdownPath: '/docs/quick-start/installation.md',
        NextBtnName: 'Installation',
        NextBtnPath: '/docs/installation',
        childrenNode: [
            {
                name: 'Installation',
                fullPath: '/docs/installation',
                markdownPath: '/docs/quick-start/installation.md',
                PreBtnName: 'Quick Start',
                PreBtnPath: '/docs/quick-start',
                NextBtnName: 'Create Application',
                NextBtnPath: '/docs/create-application',
            },
            {
                name: 'Create Application',
                fullPath: '/docs/create-application',
                markdownPath: '/docs/quick-start/create-application.md',
                PreBtnName: 'Installation',
                PreBtnPath: '/docs/installation',
                NextBtnName: 'Instance Startup',
                NextBtnPath: '/docs/startup',
            },
            {
                name: 'Startup',
                fullPath: '/docs/startup',
                markdownPath: '/docs/quick-start/instance-startup.md',
                PreBtnName: 'Create Application',
                PreBtnPath: '/docs/create-application',
                NextBtnName: 'Configuration',
                NextBtnPath: '/docs/configuration',
            },
            {
                name: 'Configuration',
                fullPath: '/docs/configuration',
                markdownPath: '/docs/quick-start/configuration.md',
                PreBtnName: 'Startup',
                PreBtnPath: '/docs/startup',
                NextBtnName: 'Example',
                NextBtnPath: '/docs/example',
            }
        ]
    },
    {
        name: "Core Component",
        fullPath: '/docs/core-component',
        markdownPath: '/docs/core-component/object-management.md',
        PreBtnName: 'Exmaple',
        PreBtnPath: '/docs/example',
        NextBtnName: 'Debug Mode',
        NextBtnPath: '/docs/core-component/debug-mode',
        childrenNode: [
            {
                name: "Object Management",
                fullPath: '/docs/core-component/object-management',
                markdownPath: '/docs/core-component/object-management.md',
                PreBtnName: 'Exmaple',
                PreBtnPath: '/docs/example',
                NextBtnName: 'Debug Mode',
                NextBtnPath: '/docs/core-component/debug-mode',
            },
            {
                name: "Debug Mode",
                fullPath: '/docs/core-component/debug-mode',
                markdownPath: '/docs/core-component/debug-mode.md',
                PreBtnName: 'Core Component | Object Management',
                PreBtnPath: '/docs/core-component/object-management',
                NextBtnName: 'Core Component | Command',
                NextBtnPath: '/docs/core-component/command',
            },
            {
                name: "Command",
                fullPath: '/docs/core-component/command',
                markdownPath: '/docs/core-component/command/command.md',
                PreBtnName: 'Core Component | Debug Mode',
                PreBtnPath: '/docs/core-component/debug-mode',
                NextBtnName: 'Command | Basic Concept',
                NextBtnPath: '/docs/core-component/command/basic-concept',
                childrenNode: [
                    {
                        name: "Basic Concept",
                        fullPath: '/docs/core-component/command/basic-concept',
                        markdownPath: '/docs/core-component/command/basic-concept.md',
                        PreBtnName: 'Core Component | Command',
                        PreBtnPath: '/docs/core-component/command',
                        NextBtnName: 'Command | Function',
                        NextBtnPath: '/docs/core-component/command/function',
                    },
                    {
                        name: "Function",
                        fullPath: '/docs/core-component/command/function',
                        markdownPath: '/docs/core-component/command/function.md',
                        PreBtnName: 'Command | Basic Concept',
                        PreBtnPath: '/docs/core-component/command/basic-concept',
                        NextBtnName: 'Command | Parser',
                        NextBtnPath: '/docs/core-component/command/parser',
                    },
                    {
                        name: "Parser",
                        fullPath: '/docs/core-component/command/parser',
                        markdownPath: '/docs/core-component/command/parser.md',
                        PreBtnName: 'Command | Function',
                        PreBtnPath: '/docs/core-component/command/function',
                        NextBtnName: 'Command | Object',
                        NextBtnPath: '/docs/core-component/command/object',
                    },
                    {
                        name: "Object",
                        fullPath: '/docs/core-component/command/object',
                        markdownPath: '/docs/core-component/command/object.md',
                        PreBtnName: 'Command | Parser',
                        PreBtnPath: '/docs/core-component/command/parser',
                        NextBtnName: 'Command | Parameter',
                        NextBtnPath: '/docs/core-component/command/parameter',
                    },
                    {
                        name: "Parameter",
                        fullPath: '/docs/core-component/command/parameter',
                        markdownPath: '/docs/core-component/command/parameter.md',
                        PreBtnName: 'Command | Object',
                        PreBtnPath: '/docs/core-component/command/object',
                        NextBtnName: 'Command | Terminal Interaction',
                        NextBtnPath: '/docs/core-component/command/terminal-interaction',
                    },
                    {
                        name: "Terminal Interaction",
                        fullPath: '/docs/core-component/command/terminal-interaction',
                        markdownPath: '/docs/core-component/command/terminal.md',
                        PreBtnName: 'Command | Parameter',
                        PreBtnPath: '/docs/core-component/command/parameter',
                        NextBtnName: 'Command | Tracing',
                        NextBtnPath: '/docs/core-component/command/tracing',
                    },
                    {
                        name: "Tracing",
                        fullPath: '/docs/core-component/command/tracing',
                        markdownPath: '/docs/core-component/command/tracing.md',
                        PreBtnName: 'Command | Terminal Interaction',
                        PreBtnPath: '/docs/core-component/command/terminal-interaction',
                        NextBtnName: 'Configuration | Overview',
                        NextBtnPath: '/docs/core-component/configuration',
                    }
                ]
            },
            {
                name: "Configuration",
                fullPath: '/docs/core-component/configuration',
                markdownPath: '/docs/core-component/configuration/overview.md',
                PreBtnName: 'Command | Tracing',
                PreBtnPath: '/docs/core-component/command/tracing',
                NextBtnName: 'Configuration | Object',
                NextBtnPath: '/docs/core-component/configuration/object',
                childrenNode: [
                    {
                        name: "Object",
                        fullPath: '/docs/core-component/configuration/object',
                        markdownPath: '/docs/core-component/configuration/object.md',
                        PreBtnName: 'Configuration | Configuration',
                        PreBtnPath: '/docs/core-component/configuration',
                        NextBtnName: 'Configuration | Config File',
                        NextBtnPath: '/docs/core-component/configuration/config-file',
                    },
                    {
                        name: "Config File",
                        fullPath: '/docs/core-component/configuration/config-file',
                        markdownPath: '/docs/core-component/configuration/config-file.md',
                        PreBtnName: 'Configuration | Object',
                        PreBtnPath: '/docs/core-component/configuration/object',
                        NextBtnName: 'Configuration | Function',
                        NextBtnPath: '/docs/core-component/configuration/function',
                    },
                    {
                        name: "Function",
                        fullPath: '/docs/core-component/configuration/function',
                        markdownPath: '/docs/core-component/configuration/function.md',
                        PreBtnName: 'Configuration | Config File',
                        PreBtnPath: '/docs/core-component/configuration/config-file',
                        NextBtnName: 'Configuration | Interface',
                        NextBtnPath: '/docs/core-component/configuration/interface-base',
                    },
                    {
                        name: "Interface",
                        fullPath: '/docs/core-component/configuration/interface-base',
                        markdownPath: '/docs/core-component/configuration/interface-base.md',
                        PreBtnName: 'Configuration | Function',
                        PreBtnPath: '/docs/core-component/configuration/function',
                        NextBtnName: 'Configuration | Adapter',
                        NextBtnPath: '/docs/core-component/configuration/adapter',
                    },
                    {
                        name: "Adapter",
                        fullPath: '/docs/core-component/configuration/adapter',
                        markdownPath: '/docs/core-component/configuration/adapter.md',
                        PreBtnName: 'Configuration | Interface',
                        PreBtnPath: '/docs/core-component/configuration/interface-base',
                        NextBtnName: 'Log | Overview',
                        NextBtnPath: '/docs/core-component/log',
                    },
                ]
            },
            {
                name: "Log",
                fullPath: '/docs/core-component/log',
                markdownPath: '/docs/core-component/log/overview.md',
                PreBtnName: 'Configuration | Adapter',
                PreBtnPath: '/docs/core-component/configuration/adapter',
                NextBtnName: 'Log | Configuration',
                NextBtnPath: '/docs/core-component/log/config',
                childrenNode: [
                    {
                        name: "Configuration",
                        fullPath: '/docs/core-component/log/config',
                        markdownPath: '/docs/core-component/log/config.md',
                        PreBtnName: 'Core Component | Log',
                        PreBtnPath: '/docs/core-component/log',
                        NextBtnName: 'Log | Level',
                        NextBtnPath: '/docs/core-component/log/level',
                    },
                    {
                        name: "Level",
                        fullPath: '/docs/core-component/log/level',
                        markdownPath: '/docs/core-component/log/level.md',
                        PreBtnName: 'Log | Config',
                        PreBtnPath: '/docs/core-component/log/config',
                        NextBtnName: 'Log | Path',
                        NextBtnPath: '/docs/core-component/log/path',
                    },
                    {
                        name: "Path",
                        fullPath: '/docs/core-component/log/path',
                        markdownPath: '/docs/core-component/log/path.md',
                        PreBtnName: 'Log | Level',
                        PreBtnPath: '/docs/core-component/log/level',
                        NextBtnName: 'Log | Chain Operation',
                        NextBtnPath: '/docs/core-component/log/chain-opts',
                    },
                    {
                        name: "Chain Operation",
                        fullPath: '/docs/core-component/log/chain-opts',
                        markdownPath: '/docs/core-component/log/chain-opts.md',
                        PreBtnName: 'Log | Path',
                        PreBtnPath: '/docs/core-component/log/path',
                        NextBtnName: 'Log | Color Print',
                        NextBtnPath: '/docs/core-component/log/color-print',
                    },
                    {
                        name: "Color Print",
                        fullPath: '/docs/core-component/log/color-print',
                        markdownPath: '/docs/core-component/log/color-print.md',
                        PreBtnName: 'Log | Chain Operation',
                        PreBtnPath: '/docs/core-component/log/chain-opts',
                        NextBtnName: 'Log | Context',
                        NextBtnPath: '/docs/core-component/log/context',
                    },
                    {
                        name: "Context",
                        fullPath: '/docs/core-component/log/context',
                        markdownPath: '/docs/core-component/log/context.md',
                        PreBtnName: 'Log | Color Print',
                        PreBtnPath: '/docs/core-component/log/color-print',
                        NextBtnName: 'Log | Handler',
                        NextBtnPath: '/docs/core-component/log/handler',
                    },
                    {
                        name: "Handler",
                        fullPath: '/docs/core-component/log/handler',
                        markdownPath: '/docs/core-component/log/handler.md',
                        PreBtnName: 'Log | Context',
                        PreBtnPath: '/docs/core-component/log/context',
                        NextBtnName: 'Log | JSON Format',
                        NextBtnPath: '/docs/core-component/log/json-format',
                    },
                    {
                        name: "JSON Format",
                        fullPath: '/docs/core-component/log/json-format',
                        markdownPath: '/docs/core-component/log/json-format.md',
                        PreBtnName: 'Log | Handler',
                        PreBtnPath: '/docs/core-component/log/handler',
                        NextBtnName: 'Log | Async',
                        NextBtnPath: '/docs/core-component/log/async',
                    },
                    {
                        name: "Async",
                        fullPath: '/docs/core-component/log/async',
                        markdownPath: '/docs/core-component/log/async.md',
                        PreBtnName: 'Log | JSON Format',
                        PreBtnPath: '/docs/core-component/log/json-format',
                        NextBtnName: 'Log | Stack Print',
                        NextBtnPath: '/docs/core-component/log/stack-print',
                    },
                    {
                        name: "Stack Print",
                        fullPath: '/docs/core-component/log/stack-print',
                        markdownPath: '/docs/core-component/log/stack-print.md',
                        PreBtnName: 'Log | Async',
                        PreBtnPath: '/docs/core-component/log/async',
                        NextBtnName: 'Log | Debug Info',
                        NextBtnPath: '/docs/core-component/log/debug-info',
                    },
                    {
                        name: "Debug Info",
                        fullPath: '/docs/core-component/log/debug-info',
                        markdownPath: '/docs/core-component/log/debug-info.md',
                        PreBtnName: 'Log | Stack Print',
                        PreBtnPath: '/docs/core-component/log/stack-print',
                        NextBtnName: 'Log | Writer',
                        NextBtnPath: '/docs/core-component/log/writer',
                    },
                    {
                        name: "Writer",
                        fullPath: '/docs/core-component/log/writer',
                        markdownPath: '/docs/core-component/log/writer.md',
                        PreBtnName: 'Log | Debug Info',
                        PreBtnPath: '/docs/core-component/log/debug-info',
                        NextBtnName: 'Log | Flags',
                        NextBtnPath: '/docs/core-component/log/flags',
                    },
                    {
                        name: "Flags",
                        fullPath: '/docs/core-component/log/flags',
                        markdownPath: '/docs/core-component/log/flags.md',
                        PreBtnName: 'Log | Writer',
                        PreBtnPath: '/docs/core-component/log/writer',
                        NextBtnName: 'Log | Rotate',
                        NextBtnPath: '/docs/core-component/log/rotate',
                    },
                    {
                        name: "Rotate",
                        fullPath: '/docs/core-component/log/rotate',
                        markdownPath: '/docs/core-component/log/rotate.md',
                        PreBtnName: 'Log | Flags',
                        PreBtnPath: '/docs/core-component/log/flags',
                        NextBtnName: 'Log | FAQ',
                        NextBtnPath: '/docs/core-component/log/faq',
                    },
                    {
                        name: "FAQ",
                        fullPath: '/docs/core-component/log/faq',
                        markdownPath: '/docs/core-component/log/faq.md',
                        PreBtnName: 'Log | Rotate',
                        PreBtnPath: '/docs/core-component/log/rotate',
                        NextBtnName: 'Error | Overview',
                        NextBtnPath: '/docs/core-component/error',
                    }
                ]
            },
            {
                name: "Error",
                fullPath: '/docs/core-component/error',
                markdownPath: '/docs/core-component/error/overview.md',
                PreBtnName: 'Log | FAQ',
                PreBtnPath: '/docs/core-component/log/faq',
                NextBtnName: 'Error | Function',
                NextBtnPath: '/docs/core-component/error/function',
                childrenNode: [
                    {
                        name: "Function",
                        fullPath: '/docs/core-component/error/function',
                        markdownPath: '/docs/core-component/error/function.md',
                        PreBtnName: 'Error | Function',
                        PreBtnPath: '/docs/core-component/error/function',
                        NextBtnName: 'Error | Compare',
                        NextBtnPath: '/docs/core-component/error/compare',
                    },
                    {
                        name: "Compare",
                        fullPath: '/docs/core-component/error/compare',
                        markdownPath: '/docs/core-component/error/compare.md',
                        PreBtnName: 'Error | Function',
                        PreBtnPath: '/docs/core-component/error/function',
                        NextBtnName: 'Error | Code',
                        NextBtnPath: '/docs/core-component/error/code',
                    },
                    {
                        name: "Code",
                        fullPath: '/docs/core-component/error/code',
                        markdownPath: '/docs/core-component/error/code.md',
                        PreBtnName: 'Error | Compare',
                        PreBtnPath: '/docs/core-component/error/compare',
                        NextBtnName: 'Error | Others',
                        NextBtnPath: '/docs/core-component/error/others',
                    },
                    {
                        name: "Others",
                        fullPath: '/docs/core-component/error/others',
                        markdownPath: '/docs/core-component/error/others.md',
                        PreBtnName: 'Error | Code',
                        PreBtnPath: '/docs/core-component/error/code',
                        NextBtnName: 'Error | Best Practices',
                        NextBtnPath: '/docs/core-component/error/best-practices',
                    },
                    {
                        name: "Best Practices",
                        fullPath: '/docs/core-component/error/best-practices',
                        markdownPath: '/docs/core-component/error/best-practices.md',
                        PreBtnName: 'Error | Others',
                        PreBtnPath: '/docs/core-component/error/others',
                        NextBtnName: 'Error | Banchmark',
                        NextBtnPath: '/docs/core-component/error/benchmark',
                    },
                    {
                        name: "Banchmark",
                        fullPath: '/docs/core-component/error/benchmark',
                        markdownPath: '/docs/core-component/error/benchmark.md',
                        PreBtnName: 'Error | Best Practices',
                        PreBtnPath: '/docs/core-component/error/best-practices',
                        NextBtnName: 'Data Validation | Overview',
                        NextBtnPath: '/docs/core-component/data-valid',
                    }
                ]
            },
            {
                name: "Data Validation",
                fullPath: '/docs/core-component/data-valid',
                markdownPath: '/docs/core-component/data-valid/overview.md',
                PreBtnName: 'Error | Banchmark',
                PreBtnPath: '/docs/core-component/error',
                NextBtnName: 'Data Validation | Rule',
                NextBtnPath: '/docs/core-component/data-valid/rule',
                childrenNode: [
                    {
                        name: "Rule",
                        fullPath: '/docs/core-component/data-valid/rule',
                        markdownPath: '/docs/core-component/data-valid/rule.md',
                        PreBtnName: 'Data Validation | Overview',
                        PreBtnPath: '/docs/core-component/data-valid/',
                        NextBtnName: 'Data Validation | Object',
                        NextBtnPath: '/docs/core-component/data-valid/object',
                    },
                    {
                        name: "Object",
                        fullPath: '/docs/core-component/data-valid/object',
                        markdownPath: '/docs/core-component/data-valid/object.md',
                        PreBtnName: 'Data Validation | Rule',
                        PreBtnPath: '/docs/core-component/data-valid/rule',
                        NextBtnName: 'Data Validation | Result',
                        NextBtnPath: '/docs/core-component/data-valid/result',
                    },
                    {
                        name: "Result",
                        fullPath: '/docs/core-component/data-valid/result',
                        markdownPath: '/docs/core-component/data-valid/result.md',
                        PreBtnName: 'Data Validation | Object',
                        PreBtnPath: '/docs/core-component/data-valid/object',
                        NextBtnName: 'Data Validation | Types',
                        NextBtnPath: '/docs/core-component/data-valid/types',
                    },
                    {
                        name: "Types",
                        fullPath: '/docs/core-component/data-valid/types',
                        markdownPath: '/docs/core-component/data-valid/types.md',
                        PreBtnName: 'Data Validation | Result',
                        PreBtnPath: '/docs/core-component/data-valid/result',
                        NextBtnName: 'Data Validation | Optional',
                        NextBtnPath: '/docs/core-component/data-valid/optional',
                    },
                    {
                        name: "Optional",
                        fullPath: '/docs/core-component/data-valid/optional',
                        markdownPath: '/docs/core-component/data-valid/optional.md',
                        PreBtnName: 'Data Validation | Types',
                        PreBtnPath: '/docs/core-component/data-valid/types',
                        NextBtnName: 'Data Validation | Recursive',
                        NextBtnPath: '/docs/core-component/data-valid/recursive',
                    },
                    {
                        name: "Recursive",
                        fullPath: '/docs/core-component/data-valid/recursive',
                        markdownPath: '/docs/core-component/data-valid/recursive.md',
                        PreBtnName: 'Data Validation | Optional',
                        PreBtnPath: '/docs/core-component/data-valid/optional',
                        NextBtnName: 'Data Validation | Custom Rule',
                        NextBtnPath: '/docs/core-component/data-valid/custom-rule',
                    },
                    {
                        name: "Custom Rule",
                        fullPath: '/docs/core-component/data-valid/custom-rule',
                        markdownPath: '/docs/core-component/data-valid/custom-rule.md',
                        PreBtnName: 'Data Validation | Recursive',
                        PreBtnPath: '/docs/core-component/data-valid/recursive',
                        NextBtnName: 'Data Validation | Custom Error',
                        NextBtnPath: '/docs/core-component/data-valid/custom-error',
                    },
                    {
                        name: "Custom Error",
                        fullPath: '/docs/core-component/data-valid/custom-error',
                        markdownPath: '/docs/core-component/data-valid/custom-error.md',
                        PreBtnName: 'Data Validation | Custom Rule',
                        PreBtnPath: '/docs/core-component/data-valid/custom-rule',
                        NextBtnName: 'Data Validation | Methods',
                        NextBtnPath: '/docs/core-component/data-valid/method',
                    },
                    {
                        name: "Methods",
                        fullPath: '/docs/core-component/data-valid/method',
                        markdownPath: '/docs/core-component/data-valid/method.md',
                        PreBtnName: 'Data Validation | Custom Error',
                        PreBtnPath: '/docs/core-component/data-valid/custom-error',
                        NextBtnName: 'Data Validation | FQA',
                        NextBtnPath: '/docs/core-component/data-valid/faq',
                    },
                    {
                        name: "FQA",
                        fullPath: '/docs/core-component/data-valid/faq',
                        markdownPath: '/docs/core-component/data-valid/faq.md',
                        PreBtnName: 'Data Validation | Methods',
                        PreBtnPath: '/docs/core-component/data-valid/method',
                        NextBtnName: ' Type Convert | Overview',
                        NextBtnPath: '/docs/core-component/type-convert',
                    }
                ]
            },
            {
                name: "Type Convert",
                fullPath: '/docs/core-component/type-convert',
                markdownPath: '/docs/core-component/type-convert/overview.md',
                PreBtnName: 'Data Validation | FQA',
                PreBtnPath: '/docs/core-component/data-valid/faq',
                NextBtnName: 'Type Convert | Basic Type',
                NextBtnPath: '/docs/core-component/type-convert/basic-type',
                childrenNode: [
                    {
                        name: "Basice Type",
                        fullPath: '/docs/core-component/type-convert/basic-type',
                        markdownPath: '/docs/core-component/type-convert/basic-type.md',
                        PreBtnName: 'Type Convert | Overview',
                        PreBtnPath: '/docs/core-component/type-convert',
                        NextBtnName: 'Type Convert | Map',
                        NextBtnPath: '/docs/core-component/type-convert/map',
                    },
                    {
                        name: "Map",
                        fullPath: '/docs/core-component/type-convert/map',
                        markdownPath: '/docs/core-component/type-convert/map.md',
                        PreBtnName: 'Type Convert | Basic Type',
                        PreBtnPath: '/docs/core-component/type-convert/basic-type',
                        NextBtnName: 'Type Convert | Struct',
                        NextBtnPath: '/docs/core-component/type-convert/struct',
                    },
                    {
                        name: "Struct",
                        fullPath: '/docs/core-component/type-convert/struct',
                        markdownPath: '/docs/core-component/type-convert/struct.md',
                        PreBtnName: 'Type Convert | Map',
                        PreBtnPath: '/docs/core-component/type-convert/map',
                        NextBtnName: 'Type Convert | Structs',
                        NextBtnPath: '/docs/core-component/type-convert/structs',
                    },
                    {
                        name: "Structs",
                        fullPath: '/docs/core-component/type-convert/structs',
                        markdownPath: '/docs/core-component/type-convert/structs.md',
                        PreBtnName: 'Type Convert | Struct',
                        PreBtnPath: '/docs/core-component/type-convert/struct',
                        NextBtnName: 'Type Convert | Scan',
                        NextBtnPath: '/docs/core-component/type-convert/scan',
                    },
                    {
                        name: "Scan",
                        fullPath: '/docs/core-component/type-convert/scan',
                        markdownPath: '/docs/core-component/type-convert/scan.md',
                        PreBtnName: 'Type Convert | Structs',
                        PreBtnPath: '/docs/core-component/type-convert/structs',
                        NextBtnName: 'Type Convert | Unmarshal',
                        NextBtnPath: '/docs/core-component/type-convert/unmarshal',
                    },
                    {
                        name: "Unmarshal",
                        fullPath: '/docs/core-component/type-convert/unmarshal',
                        markdownPath: '/docs/core-component/type-convert/unmarshal.md',
                        PreBtnName: 'Type Convert | Scan',
                        PreBtnPath: '/docs/core-component/type-convert/scan',
                        NextBtnName: 'Type Convert | Converter',
                        NextBtnPath: '/docs/core-component/type-convert/converter',
                    },
                    {
                        name: "Converter",
                        fullPath: '/docs/core-component/type-convert/converter',
                        markdownPath: '/docs/core-component/type-convert/converter.md',
                        PreBtnName: 'Type Convert | Unmarshal',
                        PreBtnPath: '/docs/core-component/type-convert/unmarshal',
                        NextBtnName: 'Type Convert | Benchmark',
                        NextBtnPath: '/docs/core-component/type-convert/benchmark',
                    },
                    {
                        name: "Benchmark",
                        fullPath: '/docs/core-component/type-convert/benchmark',
                        markdownPath: '/docs/core-component/type-convert/benchmark.md',
                        PreBtnName: 'Type Convert | Converter',
                        PreBtnPath: '/docs/core-component/type-convert/converter',
                        NextBtnName: 'Cache | Overview',
                        NextBtnPath: '/docs/core-component/cache',
                    }
                ]
            },
            {
                name: "Cache",
                fullPath: '/docs/core-component/cache',
                markdownPath: '/docs/core-component/cache/overview.md',
                PreBtnName: 'Type Convert | Benchmark',
                PreBtnPath: '/docs/core-component/type-convert/benchmark',
                NextBtnName: 'Cache | Interface',
                NextBtnPath: '/docs/core-component/cache/interface',
                childrenNode: [
                    {
                        name: "Interface",
                        fullPath: '/docs/core-component/cache/interface',
                        markdownPath: '/docs/core-component/cache/interface.md',
                        PreBtnName: 'Cache | Overview',
                        PreBtnPath: '/docs/core-component/cache',
                        NextBtnName: 'Cache | Memory Cache',
                        NextBtnPath: '/docs/core-component/cache/memory-cache',
                    },
                    {
                        name: "Memory Cache",
                        fullPath: '/docs/core-component/cache/memory-cache',
                        markdownPath: '/docs/core-component/cache/memory.md',
                        PreBtnName: 'Cache | Interface',
                        PreBtnPath: '/docs/core-component/cache/interface',
                        NextBtnName: 'Cache | Redis Cache',
                        NextBtnPath: '/docs/core-component/cache/redis-cache',
                    },
                    {
                        name: "Redis Cache",
                        fullPath: '/docs/core-component/cache/redis-cache',
                        markdownPath: '/docs/core-component/cache/redis.md',
                        PreBtnName: 'Cache | Memory Cache',
                        PreBtnPath: '/docs/core-component/cache/memory-cache',
                        NextBtnName: 'Cache | Methods',
                        NextBtnPath: '/docs/core-component/cache/methods',
                    },
                    {
                        name: "Methods",
                        fullPath: '/docs/core-component/cache/methods',
                        markdownPath: '/docs/core-component/cache/methods.md',
                        PreBtnName: 'Cache | Redis Cache',
                        PreBtnPath: '/docs/core-component/cache/redis-cache',
                        NextBtnName: 'Template Engine | Overview',
                        NextBtnPath: '/docs/core-component/template-engine/',
                    }
                ]
            },
            {
                name: "Template Engine",
                fullPath: '/docs/core-component/template-engine',
                markdownPath: '/docs/core-component/template-engine/overview.md',
                PreBtnName: 'Cache | Methods',
                PreBtnPath: '/docs/core-component/cache/methods',
                NextBtnName: 'Template Engine | Configuration',
                NextBtnPath: '/docs/core-component/template-engine/config',
                childrenNode: [
                    {
                        name: "Configuration",
                        fullPath: '/docs/core-component/template-engine/config',
                        markdownPath: '/docs/core-component/template-engine/config.md',
                        PreBtnName: 'Template Engine | Overview',
                        PreBtnPath: '/docs/core-component/template-engine/',
                        NextBtnName: 'Template Engine | Tags',
                        NextBtnPath: '/docs/core-component/template-engine/tags',
                    },
                    {
                        name: "Tags",
                        fullPath: '/docs/core-component/template-engine/tags',
                        markdownPath: '/docs/core-component/template-engine/tags.md',
                        PreBtnName: 'Template Engine | Configuration',
                        PreBtnPath: '/docs/core-component/template-engine/config',
                        NextBtnName: 'Template Engine | Basic Methods',
                        NextBtnPath: '/docs/core-component/template-engine/methods',
                    },
                    {
                        name: "Basic Methods",
                        fullPath: '/docs/core-component/template-engine/methods',
                        markdownPath: '/docs/core-component/template-engine/methods.md',
                        PreBtnName: 'Template Engine | Tags',
                        PreBtnPath: '/docs/core-component/template-engine/tags',
                        NextBtnName: 'Template Engine | Built-in Methods',
                        NextBtnPath: '/docs/core-component/template-engine/built-in-methods',
                    },
                    {
                        name: "Built-in Methods",
                        fullPath: '/docs/core-component/template-engine/built-in-methods',
                        markdownPath: '/docs/core-component/template-engine/built-in-methods.md',
                        PreBtnName: 'Template Engine | Methods',
                        PreBtnPath: '/docs/core-component/template-engine/methods',
                        NextBtnName: 'Template Engine | Customized Methods',
                        NextBtnPath: '/docs/core-component/template-engine/customized-methods',
                    },
                    {
                        name: "Customized Methods",
                        fullPath: '/docs/core-component/template-engine/customized-methods',
                        markdownPath: '/docs/core-component/template-engine/customized-methods.md',
                        PreBtnName: 'Template Engine | Built-in Methods',
                        PreBtnPath: '/docs/core-component/template-engine/built-in-methods',
                        NextBtnName: 'Template Engine | Variables',
                        NextBtnPath: '/docs/core-component/template-engine/variables',
                    },
                    {
                        name: "Variables",
                        fullPath: '/docs/core-component/template-engine/variables',
                        markdownPath: '/docs/core-component/template-engine/variables.md',
                        PreBtnName: 'Template Engine | Customized Methods',
                        PreBtnPath: '/docs/core-component/template-engine/customized-methods',
                        NextBtnName: 'Template Engine | Layout',
                        NextBtnPath: '/docs/core-component/template-engine/layout',
                    },
                    {
                        name: "Layout",
                        fullPath: '/docs/core-component/template-engine/layout',
                        markdownPath: '/docs/core-component/template-engine/layout.md',
                        PreBtnName: 'Template Engine | Variables',
                        PreBtnPath: '/docs/core-component/template-engine/variables',
                        NextBtnName: 'Template Engine | XSS',
                        NextBtnPath: '/docs/core-component/template-engine/xss',
                    },
                    {
                        name: "XSS",
                        fullPath: '/docs/core-component/template-engine/xss',
                        markdownPath: '/docs/core-component/template-engine/xss.md',
                        PreBtnName: 'Template Engine | Layout',
                        PreBtnPath: '/docs/core-component/template-engine/layout',
                        NextBtnName: 'Template Engine | Others',
                        NextBtnPath: '/docs/core-component/template-engine/others',
                    },
                    {
                        name: "Others",
                        fullPath: '/docs/core-component/template-engine/others',
                        markdownPath: '/docs/core-component/template-engine/others.md',
                        PreBtnName: 'Template Engine | XSS',
                        PreBtnPath: '/docs/core-component/orm',
                        NextBtnName: 'ORM | Overview',
                        NextBtnPath: '/docs/core-component/orm',
                    }
                ]
            },
            {
                name: "ORM",
                fullPath: '/docs/core-component/orm',
                markdownPath: '/docs/core-component/orm/overview.md',
                PreBtnName: 'Template Engine | Others',
                PreBtnPath: '/docs/core-component/template-engine/others',
                NextBtnName: 'ORM | Overview',
                NextBtnPath: '/docs/core-component/orm',
                childrenNode: [
                    {
                        name: "Configuration",
                        fullPath: '/docs/core-component/orm/config',
                        markdownPath: '/docs/core-component/orm/config.md',
                        PreBtnName: 'ORM | Overview',
                        PreBtnPath: '/docs/core-component/orm',
                        NextBtnName: 'ORM | Chain Operation',
                        NextBtnPath: '/docs/core-component/orm/chain-opts',
                    },
                    {
                        name: "Chain Operation",
                        fullPath: '/docs/core-component/orm/chain-opts',
                        markdownPath: '/docs/core-component/orm/chain-opts/overview.md',
                        PreBtnName: 'ORM | Configuration',
                        PreBtnPath: '/docs/core-component/orm/config',
                        NextBtnName: 'ORM | Model Creation',
                        NextBtnPath: '/docs/core-component/orm/chain-opts/model-creation',
                        childrenNode: [
                            {
                                name: "Model Creation",
                                fullPath: '/docs/core-component/orm/chain-opts/model-creation',
                                markdownPath: '/docs/core-component/orm/chain-opts/model-creation.md',
                                PreBtnName: 'ORM | Chain Operation',
                                PreBtnPath: '/docs/core-component/orm/chain-opts',
                                NextBtnName: 'ORM | Write',
                                NextBtnPath: '/docs/core-component/orm/chain-opts/write',
                            },
                            {
                                name: "Write",
                                fullPath: '/docs/core-component/orm/chain-opts/write',
                                markdownPath: '/docs/core-component/orm/chain-opts/write.md',
                                PreBtnName: 'ORM | Model Creation',
                                PreBtnPath: '/docs/core-component/orm/chain-opts/model-creation',
                                NextBtnName: 'ORM | Update & Delete',
                                NextBtnPath: '/docs/core-component/orm/chain-opts/update-delete',
                            },
                            {
                                name: "Update & Delete",
                                fullPath: '/docs/core-component/orm/chain-opts/update-delete',
                                markdownPath: '/docs/core-component/orm/chain-opts/update-delete.md',
                                PreBtnName: 'ORM | Write',
                                PreBtnPath: '/docs/core-component/orm/chain-opts/write',
                                NextBtnName: 'ORM | Query',
                                NextBtnPath: '/docs/core-component/orm/chain-opts/query',
                            },
                            {
                                name: "Query",
                                fullPath: '/docs/core-component/orm/chain-opts/query',
                                markdownPath: '/docs/core-component/orm/chain-opts/query/overview.md',
                                PreBtnName: 'ORM | Update & Delete',
                                PreBtnPath: '/docs/core-component/orm/chain-opts/update-delete',
                                NextBtnName: 'ORM | Where',
                                NextBtnPath: '/docs/core-component/orm/chain-opts/query/where',
                                childrenNode: [
                                    {
                                        name: "Where",
                                        fullPath: '/docs/core-component/orm/chain-opts/query/where',
                                        markdownPath: '/docs/core-component/orm/chain-opts/query/where.md',
                                        PreBtnName: 'ORM | Query',
                                        PreBtnPath: '/docs/core-component/orm/chain-opts/query',
                                        NextBtnName: 'ORM | All&One&Array&Value&Count',
                                        NextBtnPath: '/docs/core-component/orm/chain-opts/query/all-one-array-value-count',
                                    },
                                    {
                                        name: "All&One&Array&Value&Count",
                                        fullPath: '/docs/core-component/orm/chain-opts/query/all-one-array-value-count',
                                        markdownPath: '/docs/core-component/orm/chain-opts/query/all-one-array-value-count.md',
                                        PreBtnName: 'ORM | Where',
                                        PreBtnPath: '/docs/core-component/orm/chain-opts/query/where',
                                        NextBtnName: 'ORM | AllAndCount',
                                        NextBtnPath: '/docs/core-component/orm/chain-opts/query/all-count',
                                    },
                                    {
                                        name: "AllAndCount",
                                        fullPath: '/docs/core-component/orm/chain-opts/query/all-count',
                                        markdownPath: '/docs/core-component/orm/chain-opts/query/all-count.md',
                                        PreBtnName: 'ORM | All&One&Array&Value&Count',
                                        PreBtnPath: '/docs/core-component/orm/chain-opts/query/all-one-array-value-count',
                                        NextBtnName: 'ORM | Scan',
                                        NextBtnPath: '/docs/core-component/orm/chain-opts/query/scan',
                                    },
                                    {
                                        name: "Scan",
                                        fullPath: '/docs/core-component/orm/chain-opts/query/scan',
                                        markdownPath: '/docs/core-component/orm/chain-opts/query/scan.md',
                                        PreBtnName: 'ORM | AllAndCount',
                                        PreBtnPath: '/docs/core-component/orm/chain-opts/query/all-count',
                                        NextBtnName: 'ORM | ScanAndCount',
                                        NextBtnPath: '/docs/core-component/orm/chain-opts/query/scan-count',
                                    },
                                    {
                                        name: "ScanAndCount",
                                        fullPath: '/docs/core-component/orm/chain-opts/query/scan-count',
                                        markdownPath: '/docs/core-component/orm/chain-opts/query/scan-count.md',
                                        PreBtnName: 'ORM | Scan',
                                        PreBtnPath: '/docs/core-component/orm/chain-opts/query/scan',
                                        NextBtnName: 'ORM | Join',
                                        NextBtnPath: '/docs/core-component/orm/chain-opts/query/join',
                                    },
                                    {
                                        name: "Join",
                                        fullPath: '/docs/core-component/orm/chain-opts/query/join',
                                        markdownPath: '/docs/core-component/orm/chain-opts/query/join.md',
                                        PreBtnName: 'ORM | ScanAndCount',
                                        PreBtnPath: '/docs/core-component/orm/chain-opts/query/scan-count',
                                        NextBtnName: 'ORM | Group&Order&Having',
                                        NextBtnPath: '/docs/core-component/orm/chain-opts/query/group-order-having',
                                    },
                                    {
                                        name: "Group&Order&Having",
                                        fullPath: '/docs/core-component/orm/chain-opts/query/group-order-having',
                                        markdownPath: '/docs/core-component/orm/chain-opts/query/group-order-having.md',
                                        PreBtnName: 'ORM | Join',
                                        PreBtnPath: '/docs/core-component/orm/chain-opts/query/join',
                                        NextBtnName: 'ORM | Union',
                                        NextBtnPath: '/docs/core-component/orm/chain-opts/query/union',
                                    },
                                    {
                                        name: "Union",
                                        fullPath: '/docs/core-component/orm/chain-opts/query/union',
                                        markdownPath: '/docs/core-component/orm/chain-opts/query/union.md',
                                        PreBtnName: 'ORM | Group&Order&Having',
                                        PreBtnPath: '/docs/core-component/orm/chain-opts/query/group-order-having',
                                        NextBtnName: 'ORM | SubQuery',
                                        NextBtnPath: '/docs/core-component/orm/chain-opts/query/subquery',
                                    },
                                    {
                                        name: "SubQuery",
                                        fullPath: '/docs/core-component/orm/chain-opts/query/subquery',
                                        markdownPath: '/docs/core-component/orm/chain-opts/query/subquery.md',
                                        PreBtnName: 'ORM | Union',
                                        PreBtnPath: '/docs/core-component/orm/chain-opts/query/union',
                                        NextBtnName: 'ORM | Common Operation',
                                        NextBtnPath: '/docs/core-component/orm/chain-opts/common-opts',
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        name: "Framework Design",
        fullPath: '/docs/framework-design',
        markdownPath: '/docs/framework-design/module-design.md',
        NextBtnName: 'Module Design',
        NextBtnPath: '/docs/framework-design/module-design',
        childrenNode: [
            {
                name: "Module Design",
                fullPath: '/docs/framework-design/module-design',
                markdownPath: '/docs/framework-design/module-design.md',
                PreBtnName: 'Framework Design',
                PreBtnPath: '/docs/framework-design/',
                NextBtnName: 'Unified Framework Design',
                NextBtnPath: '/docs/framework-design/unified-framework-design',
            },
            {
                name: "Unified Framework Design",
                fullPath: '/docs/framework-design/unified-framework-design',
                markdownPath: '/docs/framework-design/unified-framework-design.md',
                PreBtnName: 'Module Design',
                PreBtnPath: '/docs/framework-design/module-design',
                NextBtnName: 'Project Package Design',
                NextBtnPath: '/docs/framework-design/project-package-design',
            },
            {
                name: "Project Package Design",
                fullPath: '/docs/framework-design/project-package-design',
                markdownPath: '/docs/framework-design/project-package-design.md',
                PreBtnName: 'Unified Framework Design',
                PreBtnPath: '/docs/framework-design/unified-framework-design',
                NextBtnName: 'Dao Design',
                NextBtnPath: '/docs/framework-design/dao-design',
            },
            {
                name: "Dao Design",
                fullPath: '/docs/framework-design/dao-design',
                markdownPath: '/docs/framework-design/dao-design.md',
                PreBtnName: 'Project Package Design',
                PreBtnPath: '/docs/framework-design/project-package-design',
                NextBtnName: 'constructure Design',
                NextBtnPath: '/docs/framework-design/constructure-design',
            },
            {
                name: "constructure Design",
                fullPath: '/docs/framework-design/constructure-design',
                markdownPath: '/docs/framework-design/constructure-design.md',
                PreBtnName: 'Dao Design',
                PreBtnPath: '/docs/framework-design/dao-design',
                NextBtnName: 'Data&Bz model',
                NextBtnPath: '/docs/framework-design/data-bz-model',
            },
            {
                name: "Data&Bz model",
                fullPath: '/docs/framework-design/data-bz-model',
                markdownPath: '/docs/framework-design/data-bz-model.md',
                PreBtnName: 'constructure Design',
                PreBtnPath: '/docs/framework-design/constructure-design',
                NextBtnName: 'Microservice',
                NextBtnPath: '/docs/framework-design/microservice',
            },
            {
                name: "Microservice",
                fullPath: '/docs/framework-design/microservice',
                markdownPath: '/docs/framework-design/microservice.md',
                PreBtnName: 'Data&Bz model',
                PreBtnPath: '/docs/framework-design/data-bz-model',
                NextBtnName: 'Tracing Design',
                NextBtnPath: '/docs/framework-design/tracing-design',
            },
            {
                name: "Tracing Design",
                fullPath: '/docs/framework-design/tracing-design',
                markdownPath: '/docs/framework-design/tracing-design.md',
                PreBtnName: 'Microservice',
                PreBtnPath: '/docs/framework-design/microservice',
                NextBtnName: 'Error Design',
                NextBtnPath: '/docs/framework-design/error-design',
            },
            {
                name: "Error Design",
                fullPath: '/docs/framework-design/error-design',
                markdownPath: '/docs/framework-design/error-design.md',
                PreBtnName: 'Tracing Design',
                PreBtnPath: '/docs/framework-design/tracing-design',
                NextBtnName: 'Interface&Generic',
                NextBtnPath: '/docs/framework-design/interface-generic-design',
            },
            {
                name: "Interface&Generic",
                fullPath: '/docs/framework-design/interface-generic-design',
                markdownPath: '/docs/framework-design/interface-generic-design.md',
                PreBtnName: 'Error Design',
                PreBtnPath: '/docs/framework-design/error-design',
                NextBtnName: 'Implict&Explicit',
                NextBtnPath: '/docs/framework-design/implict-explicit-init',
            },
            {
                name: "Implict&Explicit",
                fullPath: '/docs/framework-design/implict-explicit-init',
                markdownPath: '/docs/framework-design/implict-explicit-init.md',
                PreBtnName: 'Interface&Generic',
                PreBtnPath: '/docs/framework-design/interface-generic-design',
                NextBtnName: 'Context',
                NextBtnPath: '/docs/framework-design/context-design',
            },
            {
                name: "Context",
                fullPath: '/docs/framework-design/context-design',
                markdownPath: '/docs/framework-design/context-design.md',
                PreBtnName: 'Implict&Explicit',
                PreBtnPath: '/docs/framework-design/implict-explicit-init',
                NextBtnName: 'Enum',
                NextBtnPath: '/docs/framework-design/enum-management',
            },
            {
                name: "Enum",
                fullPath: '/docs/framework-design/enum-management',
                markdownPath: '/docs/framework-design/enum-management.md',
                PreBtnName: 'Context',
                PreBtnPath: '/docs/framework-design/context-design',
                NextBtnName: 'Framework Design',
                NextBtnPath: '/docs/framework-design/module-design',
            }
        ]
    }
]
